/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./src/components/Logo/Logo.vue')['default']
    MenuCard: typeof import('./src/components/MenuCard/MenuCard.vue')['default']
    Navigation: typeof import('./src/components/Navigation/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/SearchBar.vue')['default']
    Setting: typeof import('./src/components/Setting/Setting.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
    Wallpaper: typeof import('./src/components/Wallpaper/Wallpaper.vue')['default']
  }
}
