/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionSheet: typeof import('./src/components/ActionSheet/ActionSheet.vue')['default']
    AnimateInput: typeof import('./src/components/AnimateInput/AnimateInput.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/ColorPicker.vue')['default']
    CropImage: typeof import('./src/components/CropImage/CropImage.vue')['default']
    CustomTitle: typeof import('./src/components/CustomTitle/CustomTitle.vue')['default']
    MenuCard: typeof import('./src/components/MenuCard/MenuCard.vue')['default']
    RadioTaget: typeof import('./src/components/RadioTaget/RadioTaget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
